require("personal.plugin_configs.telescope")
require("personal.plugin_configs.mason")
require("personal.plugin_configs.lsp_config")
require("personal.plugin_configs.treesitter")
require("personal.plugin_configs.nvim-tree")
require("personal.plugin_configs.neodev")
require("personal.plugin_configs.completions")
